"""Add percentage and amount discounts to Voucher

Revision ID: 707370bf3a2d
Revises: 07cfb2ac0069
Create Date: 2026-01-03 10:55:53.804520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707370bf3a2d'
down_revision: Union[str, Sequence[str], None] = '07cfb2ac0069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('total_discount', sa.Float(), nullable=True))
    op.add_column('vouchers', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('vouchers', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.drop_column('vouchers', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('vouchers', 'discount_amount')
    op.drop_column('vouchers', 'discount_percentage')
    op.drop_column('vouchers', 'total_discount')
    # ### end Alembic commands ###
