"""Add product discount fields to Stock table

Revision ID: d0610159f4d5
Revises: 707370bf3a2d
Create Date: 2026-01-03 11:08:35.042647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0610159f4d5'
down_revision: Union[str, Sequence[str], None] = '707370bf3a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('discount_start_date', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('discount_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'discount_end_date')
    op.drop_column('stock', 'discount_start_date')
    op.drop_column('stock', 'discount_percent')
    # ### end Alembic commands ###
